// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCs7urtpr12tHfbKRWa7ctmRdQbtkW8hQ',
    appId: '1:303942612229:web:c4aac70b58ff106097336c',
    messagingSenderId: '303942612229',
    projectId: 'laptopharbor-9593d',
    authDomain: 'laptopharbor-9593d.firebaseapp.com',
    storageBucket: 'laptopharbor-9593d.firebasestorage.app',
    measurementId: 'G-YEFNPQ32K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXazLu4UNW4sO2ms1AjvEzPt3hEiiPLs',
    appId: '1:303942612229:android:ba8d0316d1fb582f97336c',
    messagingSenderId: '303942612229',
    projectId: 'laptopharbor-9593d',
    storageBucket: 'laptopharbor-9593d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGj3mog0IasIArA6tHFVlpKADB6tmIckI',
    appId: '1:303942612229:ios:fbae2ff91fad89fb97336c',
    messagingSenderId: '303942612229',
    projectId: 'laptopharbor-9593d',
    storageBucket: 'laptopharbor-9593d.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGj3mog0IasIArA6tHFVlpKADB6tmIckI',
    appId: '1:303942612229:ios:fbae2ff91fad89fb97336c',
    messagingSenderId: '303942612229',
    projectId: 'laptopharbor-9593d',
    storageBucket: 'laptopharbor-9593d.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCs7urtpr12tHfbKRWa7ctmRdQbtkW8hQ',
    appId: '1:303942612229:web:2cf35bded740729897336c',
    messagingSenderId: '303942612229',
    projectId: 'laptopharbor-9593d',
    authDomain: 'laptopharbor-9593d.firebaseapp.com',
    storageBucket: 'laptopharbor-9593d.firebasestorage.app',
    measurementId: 'G-5KRMJ4R4M7',
  );
}
