// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6sbe-fNkt_j2HAgOLDaK9xlRFvr9QdNk',
    appId: '1:931321051678:web:8d1954cd4ba2e0d3b6cc0f',
    messagingSenderId: '931321051678',
    projectId: 'urbanharmony-4693a',
    authDomain: 'urbanharmony-4693a.firebaseapp.com',
    storageBucket: 'urbanharmony-4693a.firebasestorage.app',
    measurementId: 'G-MQ6MVDWKS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAuQiHurNhtzaCTMxu63YVGCp8v_bEGI',
    appId: '1:931321051678:android:6b215c037a35382eb6cc0f',
    messagingSenderId: '931321051678',
    projectId: 'urbanharmony-4693a',
    storageBucket: 'urbanharmony-4693a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NpA85VoVkNi7JC5nNKCxDPs9tDMrl-o',
    appId: '1:931321051678:ios:f39b66d666c8f00fb6cc0f',
    messagingSenderId: '931321051678',
    projectId: 'urbanharmony-4693a',
    storageBucket: 'urbanharmony-4693a.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NpA85VoVkNi7JC5nNKCxDPs9tDMrl-o',
    appId: '1:931321051678:ios:f39b66d666c8f00fb6cc0f',
    messagingSenderId: '931321051678',
    projectId: 'urbanharmony-4693a',
    storageBucket: 'urbanharmony-4693a.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6sbe-fNkt_j2HAgOLDaK9xlRFvr9QdNk',
    appId: '1:931321051678:web:42ea5889d570c11db6cc0f',
    messagingSenderId: '931321051678',
    projectId: 'urbanharmony-4693a',
    authDomain: 'urbanharmony-4693a.firebaseapp.com',
    storageBucket: 'urbanharmony-4693a.firebasestorage.app',
    measurementId: 'G-H939Y68Y2M',
  );
}
